# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: ✨ Setup Hugo
        env:
          HUGO_VERSION: 0.92.2
        run: |
          mkdir ~/hugo
          cd ~/hugo
          curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" --output hugo.tar.gz
          tar -xvzf hugo.tar.gz
          sudo mv hugo /usr/local/bin        
      - name: 🛠️ Build
        run: echo "hugo server -D"
      - name: 🚀 Deploy
        #run: rsync --archive -e 'ssh' 'hugo/public/' ${{ secrets.AWS_PASSWORD }} ec2-user@ec2-44-211-74-142.compute-1.amazonaws.com:~/www/
        run: |
           ssh -i ~/.ssh/pkey ec2-user@ec2-44-211-74-142.compute-1.amazonaws.com
           exit
           #scp -i ~/.ssh/pkey -r ~/myblog/myfirstweek/public/* ec2-user@ec2-44-211-74-142.compute-1.amazonaws.com:/home/ec2-user/w3
